// <auto-generated />
using HierarchyAccountsSystem.BusinessLogic.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HierarchyAccountsSystem.Api.Migrations
{
    [DbContext(typeof(HASDbContext))]
    partial class HASDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("AccountIdSequence");

            modelBuilder.Entity("HierarchyAccountsSystem.BusinessLogic.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedNever()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("AccountNodePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("AccountNodePath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentAccountId")
                        .HasColumnType("int")
                        .HasColumnName("ParentAccountID");

                    b.HasKey("AccountId");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("Accounts", t =>
                        {
                            t.HasTrigger("trg_Accounts_CycleProtection");

                            t.HasCheckConstraint("CK_AccountNodes_MaxDepth", "(LEN(AccountNodePath) - LEN(REPLACE(AccountNodePath, '/', ''))) <= 5");

                            t.HasCheckConstraint("CK_AccountNodes_RootPath", "(ParentAccountID IS NOT NULL) OR (AccountNodePath = '/')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("HierarchyAccountsSystem.BusinessLogic.Models.Account", b =>
                {
                    b.HasOne("HierarchyAccountsSystem.BusinessLogic.Models.Account", "ParentAccount")
                        .WithMany("Children")
                        .HasForeignKey("ParentAccountId")
                        .HasConstraintName("FK_AccountNodes_Parent");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("HierarchyAccountsSystem.BusinessLogic.Models.Account", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
